// use the nuxt crawler to add dynamic pages to the sitemap automatically
// https://timbenniks.dev/writings/easy-dynamic-routes-in-your-nuxt-sitemap/
// https://github.com/nuxt-community/sitemap-module/issues/143

export default function () {
  this.nuxt.hook('generate:done', (context) => {
    // URLs generated by crawler
    let generated = Array.from(context.generatedRoutes ?? []);

    // routes defined by user in nuxt sitemap config
    let definedRoutes = this.nuxt.options.sitemap.routes ?? [];

    // excludes defined by user in nuxt sitemap config
    let excludeUrls = this.nuxt.options.sitemap.exclude ?? [];

    let definedRoute;
    let routes = generated.filter((routeUrl) => {
      // drop all excluded URLs
      if (excludeUrls.includes(routeUrl)) {
        return false;
      }

      // is there a defined route for that generated URL?
      definedRoute = definedRoutes.find((item) => {
        if (typeof item === 'string') {
          return item === routeUrl;
        }
        return item.url === routeUrl;
      });

      if (definedRoute != null) {
        // yes: drop it in favor of the defined route
        return false;
      }

      // no: keep generated URL in sitemap
      return true;
    });

    this.nuxt.options.sitemap.routes = [...definedRoutes, ...routes];
  });
}
