"$schema" = "./node_modules/wrangler/config-schema.json"

send_metrics = false
compatibility_date = "2026-02-01"
name = "monsterbuddy-dynamic"
workers_dev = true
preview_urls = true

main = "./.output/server/index.mjs"

[assets]
binding = "ASSETS"
directory = "./.output/public"
html_handling = "drop-trailing-slash"
not_found_handling = "none"
