"$schema" = "./node_modules/wrangler/config-schema.json"

send_metrics = false
compatibility_date = "2026-02-01"
name = "monsterbuddy"
workers_dev = true
preview_urls = true

[assets]
directory = "./.output/public"
